### ISSUE TITLE
Setting clocks per tick and 32nd notes per beat in Time Signature meta event

### ISSUE THREAD

**Issue by sevagh** [celtera/libremidi#120]
Hello!

II noticed the time signature meta-event hardcodes the last 2 arguments (clocks per tick, 32nd notes per beat) to the values {1, 96} in the time_signature meta-event:
```
  static message time_signature(int numerator, int denominator)
  {
    int n = 1;
    int powTwo = 0;

    while (n < denominator)
    {
      n <<= 1;
      ++powTwo;
    }

    return {0xff, 0x58, 0x04, static_cast<uint8_t>(numerator), static_cast<uint8_t>(powTwo),
            1,    96};
  }
```
Maybe it can take optional parameters with defaults? e.g. `int clocks_per_tick = 24, int 32nd_notes_per_beat = 8`?

Also, are {1, 96} placeholders? From my research, {24, 8} are more typical.

**Comment by jcelerier** [comment]
heya! this can be traced back to https://github.com/ddiakopoulos/modern-midi/blob/67944e958483af32d5c39eabf6c59d4d5ec81866/src/midi_message.h#L295 ; i honestly never used these functions so didn't notice it. I'm going to add them as custom parameters - the default will not change though in order to not break silently for current users.

**Comment by sevagh** [comment]
I see you made the change: https://github.com/celtera/libremidi/commit/58ba0f870146669c1a732d1b17b1ea6ccab754cd

Thanks! Let me test this in my project and I'll close the issue asap.

**Comment by jcelerier** [comment]
yep, thanks for the notice and suggestion !
